import { useEffect, useState } from "react";
import { FiActivity, FiCalendar, FiUsers } from "react-icons/fi";
import { Link } from "react-router-dom";
import api from "../../api/axios";
import StatCard from "../../components/StatCard";

export default function MentorDashboard() {
  const [data, setData] = useState(null);
  useEffect(() => { api.get("/admin/mentor-dashboard").then((res) => setData(res.data)); }, []);
  if (!data) return <p className="text-sm text-slate-500">Loading mentor dashboard...</p>;
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><StatCard label="Assigned Batches" value={data.assigned_batches.length} icon={FiCalendar} /><StatCard label="Students in Batches" value={data.total_students} icon={FiUsers} tone="gold" /><StatCard label="Active Sessions" value={data.active_sessions.length} icon={FiActivity} tone="slate" /></div><section className="surface p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-black text-ink">My Sessions</h2><p className="mt-1 text-sm text-slate-500">You can only activate, close, and monitor sessions assigned to your account.</p></div><Link className="btn-primary" to="/admin/attendance-permission">Manage Sessions</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{data.active_sessions.map((session) => <div className="rounded-md bg-teal-50 p-4" key={session.id}><p className="font-black text-teal-800">{session.session_type} · {session.subject || "Attendance Session"}</p><p className="mt-1 text-sm text-teal-700">{session.start_time} – {session.end_time}</p></div>)}{!data.active_sessions.length && <p className="text-sm text-slate-500">No active sessions assigned to you today.</p>}</div></section><section className="surface overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-black text-ink">Students Needing Attention</h2></div><div className="table-wrap border-0 shadow-none"><table className="data-table"><thead><tr><th>Student</th><th>Batch</th><th>Class</th><th>Mentoring</th><th>Overall</th></tr></thead><tbody className="divide-y divide-slate-100">{data.low_attendance_students.map((student) => <tr key={student.id}><td><p className="font-bold text-ink">{student.full_name}</p><p className="text-xs text-slate-500">{student.student_id}</p></td><td>{student.batch}</td><td>{student.progress.class_percentage}%</td><td>{student.progress.mentoring_percentage}%</td><td>{student.progress.attendance_percentage}%</td></tr>)}{!data.low_attendance_students.length && <tr><td colSpan="5" className="py-10 text-center text-slate-500">No low-attendance students in your assigned batches.</td></tr>}</tbody></table></div></section></div>;
}
